<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
/**
 * Module_skeleton module
 *
 * @copyright       The XOOPS Project http://sourceforge.net/projects/xoops/
 * @license         GNU GPL 2 or later (http://www.gnu.org/licenses/gpl-2.0.html)
 * @package         module_skeleton
 * @since           1.00
 * @author          Xoops Development Team
 * @version         svn:$id$
 */

defined('XOOPS_ROOT_PATH') || die('XOOPS root path not defined');

$modversion['name']           = _MI_MODULE_SKELETON_NAME;
$modversion['version']        = 0.01;
$modversion['description']    = _MI_MODULE_SKELETON_DESC;
$modversion['author']         = _MI_MODULE_SKELETON_AUTHOR;
$modversion['credits']        = _MI_MODULE_SKELETON_CREDITS;
$modversion['help']           = 'page=help';
$modversion['license']        = 'GNU GPL 2.0 or later';
$modversion['license_url']    = "http://www.gnu.org/licenses/gpl-2.0.html";
$modversion['image']          = "assets/images/module_logo.png"; // Path and name of the module’s logo
$modversion['dirname']        = basename(dirname(__FILE__));
$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16']        = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = 'Frameworks/moduleclasses/icons/32';

$modversion['official']    = false;

include_once XOOPS_ROOT_PATH . "/modules/" . $modversion['dirname'] . "/include/constants.php";

// About
$modversion["module_status"]       = "Alpha";
$modversion['release_date']        = '2014/11/05'; // YYYY/mm/dd
$modversion["module_website_url"]  = "http://www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion['min_php']             = '5.3.7';
$modversion['min_xoops']           = '2.5.7';
$modversion['min_admin']           = '1.1';
$modversion['min_db']              = array(
    'mysql'  => '5.0.7',
    'mysqli' => '5.0.7'
);



// Install, update, unistall
$modversion['onInstall']   = 'include/oninstall.php';
$modversion['onUpdate']    = 'include/onupdate.php';
$modversion['onUninstall'] = 'include/onuninstall.php';



// Help files
$i                                     = 0;
$modversion['helpsection'][$i]['name'] = _MI_MODULE_SKELETON_HELP_OVERVIEW;
$modversion['helpsection'][$i]['link'] = "page=overview";
++$i;
$modversion['helpsection'][$i]['name'] = _MI_MODULE_SKELETON_HELP_INSTALL;
$modversion['helpsection'][$i]['link'] = "page=install";
++$i;
$modversion['helpsection'][$i]['name'] = _MI_MODULE_SKELETON_HELP_TIPS_TRICKS;
$modversion['helpsection'][$i]['link'] = "page=tips_tricks";



// Admin things
$modversion['hasAdmin']   = true;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu']  = "admin/menu.php";
// If you want your module has a sub menu in system menu set it to 1
$modversion['system_menu'] = true;



// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
// Tables created by sql file (without prefix!)
$i                        = 0;
$modversion['tables'][$i] = $modversion['dirname'] . '_itemcategories';
++$i;
$modversion['tables'][$i] = $modversion['dirname'] . '_items';
++$i;
$modversion['tables'][$i] = $modversion['dirname'] . '_itemfieldcategories';
++$i;
$modversion['tables'][$i] = $modversion['dirname'] . '_itemfields';



// Search
$modversion['hasSearch']      = true;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = $modversion["dirname"] . '_search';



// Menu
$modversion['hasMain']     = true;
$modversion['system_menu'] = true;
/*
global $xoopsModule, $xoopsModuleConfig, $xoopsUser;
// check if submission is allowed
$isSubmissionAllowed = false;
if (is_object($xoopsModule) && $xoopsModule->dirname() == $modversion['dirname'] && $xoopsModule->isactive()) {
    if (is_object($xoopsUser)
        && ($xoopsModuleConfig['submissions'] == _MODULE_SKELETON_SUBMISSIONS_DOWNLOAD
            || $xoopsModuleConfig['submissions'] == _MODULE_SKELETON_SUBMISSIONS_BOTH)
    ) {
        // if user is a registered user
        $groups = $xoopsUser->getGroups();
        if (count(array_intersect($xoopsModuleConfig['submitarts'], $groups)) > 0) {
            $isSubmissionAllowed = true;
        }
    } else {
        // if user is anonymous
        if ($xoopsModuleConfig['anonpost'] == _MODULE_SKELETON_ANONPOST_DOWNLOAD || $xoopsModuleConfig['anonpost'] == _MODULE_SKELETON_ANONPOST_BOTH) {
            $isSubmissionAllowed = true;
        }
    }
}
$i = 0;
if ($isSubmissionAllowed) {
    ++$i;
    $modversion['sub'][$i]['name'] = _MI_MODULE_SKELETON_SMNAME1;
    $category_suffix               = (!empty($_GET['cid'])) ? "?cid=" . intval($_GET['cid']) : ""; //Added by Lankford on 2008/2/20
    $modversion['sub'][$i]['url']  = "submit.php{$category_suffix}";
}
unset($i);
*/
$i = 0;
$modversion['sub'][$i]['name'] = _MI_MODULE_SKELETON_SUBMENU_ITEMCATEGORIES;
$modversion['sub'][$i]['url']  = "itemcategory.php";
++$i;
$modversion['sub'][$i]['name'] = _MI_MODULE_SKELETON_SUBMENU_ITEMS;
$modversion['sub'][$i]['url']  = "item.php";
++$i;



// Blocks
$i                                       = 0;
$modversion['blocks'][$i]['file']        = "top.php";
$modversion['blocks'][$i]['name']        = _MI_MODULE_SKELETON_BNAME1;
$modversion['blocks'][$i]['description'] = "Shows recently added download files";
$modversion['blocks'][$i]['show_func']   = $modversion['dirname'] . "_top_show";
$modversion['blocks'][$i]['edit_func']   = $modversion['dirname'] . "_top_edit";
$modversion['blocks'][$i]['options']     = "published|10|19";
$modversion['blocks'][$i]['template']    = $modversion['dirname'] . "_block_new.tpl";
++$i;
$modversion['blocks'][$i]['file']        = "top.php";
$modversion['blocks'][$i]['name']        = _MI_MODULE_SKELETON_BNAME2;
$modversion['blocks'][$i]['description'] = "Shows most downloaded files";
$modversion['blocks'][$i]['show_func']   = $modversion['dirname'] . "_top_show";
$modversion['blocks'][$i]['edit_func']   = $modversion['dirname'] . "_top_edit";
$modversion['blocks'][$i]['options']     = "hits|10|19";
$modversion['blocks'][$i]['template']    = $modversion['dirname'] . "_block_top.tpl";
++$i;
$modversion['blocks'][$i]['file']        = "top_by_cat.php";
$modversion['blocks'][$i]['name']        = _MI_MODULE_SKELETON_BNAME3;
$modversion['blocks'][$i]['description'] = "Shows most downloaded files by top categories";
$modversion['blocks'][$i]['show_func']   = $modversion['dirname'] . "_top_by_itemcategory_show";
$modversion['blocks'][$i]['edit_func']   = $modversion['dirname'] . "_top_by_itemcategory_edit";
$modversion['blocks'][$i]['options']     = "hits|10|19";
$modversion['blocks'][$i]['template']    = $modversion['dirname'] . "_block_top_by_cat.tpl";



// Templates
$i                                          = 0;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_header.tpl';
$modversion['templates'][$i]['description'] = 'Header info';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_footer.tpl';
$modversion['templates'][$i]['description'] = 'Footer info';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_index.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_item.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_itemcategory.tpl';
$modversion['templates'][$i]['description'] = '';

// Admin templates
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_admin_itemcategories_list.tpl';
$modversion['templates'][$i]['type']        = 'admin';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_admin_items_list.tpl';
$modversion['templates'][$i]['type']        = 'admin';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_admin_itemfieldcategories_list.tpl';
$modversion['templates'][$i]['type']        = 'admin';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_admin_itemfields_list.tpl';
$modversion['templates'][$i]['type']        = 'admin';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_admin_permissions.tpl';
$modversion['templates'][$i]['type']        = 'admin';
$modversion['templates'][$i]['description'] = '';



// Module config setting
xoops_load('XoopsEditorHandler');
$editor_handler         = XoopsEditorHandler::getInstance();
$editorList             = array_flip($editor_handler->getList());
$modversion['config'][] = array(
    'name'        => 'editor_options',
    'title'       => '_MI_MODULE_SKELETON_EDITOR',
    'description' => '_MI_MODULE_SKELETON_EDITOR_DESC',
    'formtype'    => 'select',
    'valuetype'   => 'text',
    'options'     => $editorList,
    'default'     => 'dhtmltextarea'
);

$modversion['config'][] = array(
    'name'        => 'perpage',
    'title'       => '_MI_MODULE_SKELETON_PERPAGE',
    'description' => '_MI_MODULE_SKELETON_PERPAGE_DESC',
    'formtype'    => 'select',
    'valuetype'   => 'int',
    'options'     => array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50),
    'default'     => 10
);

$modversion['config'][] = array(
    'name'        => 'admin_perpage',
    'title'       => '_MI_MODULE_SKELETON_ADMINPERPAGE',
    'description' => '_MI_MODULE_SKELETON_ADMINPERPAGE_DESC',
    'formtype'    => 'select',
    'valuetype'   => 'int',
    'options'     => array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50),
    'default'     => 10
);

$modversion['config'][] = array(
    'name'        => 'dateFormat',
    'title'       => '_MI_MODULE_SKELETON_DATEFORMAT',
    'description' => '_MI_MODULE_SKELETON_DATEFORMAT_DESC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => _DATESTRING
); //'D, d-M-Y');

$modversion['config'][] = array(
    'name'        => 'uploadPath',
    'title'       => '_MI_MODULE_SKELETON_UPLOADPATH',
    'description' => '_MI_MODULE_SKELETON_UPLOADPATH_DESC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => XOOPS_ROOT_PATH . '/uploads/' . $modversion['dirname']
);

$modversion['config'][] = array(
    'name'        => 'uploadMaxFileSize',
    'title'       => '_MI_MODULE_SKELETON_UPLOADMAXFILESIZE',
    'description' => '_MI_MODULE_SKELETON_UPLOADMAXFILESIZE_DESC',
    'formtype'    => 'textbox',
    'valuetype'   => 'int',
    'default'     => (min((int) (ini_get('upload_max_filesize')), (int) (ini_get('post_max_size')), (int) (ini_get('memory_limit')))) * 1024 * 1024 // php.ini max file size
);



// Comments
$modversion['hasComments']             = true;
$modversion['comments']['itemName']    = 'lid';
$modversion['comments']['pageName']    = 'singlefile.php';
$modversion['comments']['extraParams'] = array('cid');
// Comment callback functions
$modversion['comments']['callbackFile']        = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = $modversion['dirname'] . '_com_approve';
$modversion['comments']['callback']['update']  = $modversion['dirname'] . '_com_update';



// Notification
$modversion['hasNotification']             = true;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = $modversion['dirname'] . '_notify_iteminfo';

$i                                                            = 0;
$modversion['notification']['category'][$i]['name']           = 'global';
$modversion['notification']['category'][$i]['title']          = _MI_MODULE_SKELETON_GLOBAL_NOTIFY;
$modversion['notification']['category'][$i]['description']    = _MI_MODULE_SKELETON_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][$i]['item_name']      = '';
$modversion['notification']['category'][$i]['subscribe_from'] = array('index.php', 'viewcat.php', 'singlefile.php');
++$i;
$modversion['notification']['category'][$i]['name']           = 'category';
$modversion['notification']['category'][$i]['title']          = _MI_MODULE_SKELETON_ITEMCATEGORY_NOTIFY;
$modversion['notification']['category'][$i]['description']    = _MI_MODULE_SKELETON_ITEMCATEGORY_NOTIFYDSC;
$modversion['notification']['category'][$i]['subscribe_from'] = array('viewcat.php', 'singlefile.php');
$modversion['notification']['category'][$i]['item_name']      = 'cid';
$modversion['notification']['category'][$i]['allow_bookmark'] = true;
++$i;
$modversion['notification']['category'][$i]['name']           = 'file';
$modversion['notification']['category'][$i]['title']          = _MI_MODULE_SKELETON_FILE_NOTIFY;
$modversion['notification']['category'][$i]['description']    = _MI_MODULE_SKELETON_FILE_NOTIFYDSC;
$modversion['notification']['category'][$i]['subscribe_from'] = 'singlefile.php';
$modversion['notification']['category'][$i]['item_name']      = 'lid';
$modversion['notification']['category'][$i]['allow_bookmark'] = true;

$i                                                        = 0;
$modversion['notification']['event'][$i]['name']          = 'new_itemcategory';
$modversion['notification']['event'][$i]['category']      = 'global';
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_GLOBAL_NEWITEMCATEGORY_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_GLOBAL_NEWITEMCATEGORY_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_GLOBAL_NEWITEMCATEGORY_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_newitemcategory_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_GLOBAL_NEWITEMCATEGORY_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'file_modify';
$modversion['notification']['event'][$i]['category']      = 'global';
$modversion['notification']['event'][$i]['admin_only']    = true;
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFY_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFY_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFY_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_filemodify_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFY_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'file_broken';
$modversion['notification']['event'][$i]['category']      = 'global';
$modversion['notification']['event'][$i]['admin_only']    = true;
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_GLOBAL_FILEBROKEN_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_GLOBAL_FILEBROKEN_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_GLOBAL_FILEBROKEN_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_filebroken_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_GLOBAL_FILEBROKEN_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'file_submit';
$modversion['notification']['event'][$i]['category']      = 'global';
$modversion['notification']['event'][$i]['admin_only']    = true;
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_GLOBAL_FILESUBMIT_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_GLOBAL_FILESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_GLOBAL_FILESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_filesubmit_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_GLOBAL_FILESUBMIT_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'new_file';
$modversion['notification']['event'][$i]['category']      = 'global';
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_GLOBAL_NEWFILE_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_GLOBAL_NEWFILE_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_GLOBAL_NEWFILE_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_newfile_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_GLOBAL_NEWFILE_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'file_submit';
$modversion['notification']['event'][$i]['category']      = 'itemcategory';
$modversion['notification']['event'][$i]['admin_only']    = true;
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_ITEMCATEGORY_FILESUBMIT_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_ITEMCATEGORY_FILESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_ITEMCATEGORY_FILESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'itemcategory_filesubmit_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_ITEMCATEGORY_FILESUBMIT_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'new_file';
$modversion['notification']['event'][$i]['category']      = 'itemcategory';
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_ITEMCATEGORY_NEWFILE_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_ITEMCATEGORY_NEWFILE_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_ITEMCATEGORY_NEWFILE_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'itemcategory_newfile_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_ITEMCATEGORY_NEWFILE_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'approve';
$modversion['notification']['event'][$i]['category']      = 'file';
$modversion['notification']['event'][$i]['invisible']     = true;
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_FILE_APPROVE_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_FILE_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_FILE_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'file_approve_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_FILE_APPROVE_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'filemodified';
$modversion['notification']['event'][$i]['category']      = 'file';
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_FILE_FILEMODIFIED_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_FILE_FILEMODIFIED_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_FILE_FILEMODIFIED_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'file_filemodified_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_FILE_FILEMODIFIED_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'filemodified';
$modversion['notification']['event'][$i]['category']      = 'itemcategory';
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_ITEMCATEGORY_FILEMODIFIED_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_ITEMCATEGORY_FILEMODIFIED_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_ITEMCATEGORY_FILEMODIFIED_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'itemcategory_filemodified_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_ITEMCATEGORY_FILEMODIFIED_NOTIFYSBJ;
++$i;
$modversion['notification']['event'][$i]['name']          = 'filemodified';
$modversion['notification']['event'][$i]['category']      = 'global';
$modversion['notification']['event'][$i]['title']         = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFIED_NOTIFY;
$modversion['notification']['event'][$i]['caption']       = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFIED_NOTIFYCAP;
$modversion['notification']['event'][$i]['description']   = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFIED_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_filemodified_notify';
$modversion['notification']['event'][$i]['mail_subject']  = _MI_MODULE_SKELETON_GLOBAL_FILEMODIFIED_NOTIFYSBJ;
